// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5HngeDnxsQiPUN_FKt-V6qfc5brXtn90',
    appId: '1:228876194121:web:5de3b5c6b8f546aeec4a98',
    messagingSenderId: '228876194121',
    projectId: 'signin-ab41f',
    authDomain: 'signin-ab41f.firebaseapp.com',
    databaseURL: 'https://signin-ab41f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signin-ab41f.appspot.com',
    measurementId: 'G-JE5WE0B8NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPl5i2-dOQCe9e7Q3yjE4Jnba_s6HQpI',
    appId: '1:228876194121:android:5f7588a13456c0d9ec4a98',
    messagingSenderId: '228876194121',
    projectId: 'signin-ab41f',
    databaseURL: 'https://signin-ab41f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signin-ab41f.appspot.com',
  );
}
